---
- hosts: localhost
  vars:
  - warName: java-example-0.0.1-SNAPSHOT.war
  - tomcat_version: 10.1.7
  - warRemotePath: /opt/apache-tomcat-{{ tomcat_version }}/webapps

  tasks:
  - name: Copy WAR to Remote server
    remote_src: True
    copy: src=target/{{ warName }} dest={{ warRemotePath }}/{{ warName }} owner=labsuser group=labsuser
